/**
 * HS 4-digit Heading code → human-readable name.
 *
 * Generated from UN Comtrade's reference H6 classification
 * (https://comtradeapi.un.org/files/v1/app/reference/H6.json).
 * Names trimmed to the first phrase (split on `;`) and capped at
 * 60 chars to keep tooltip rows readable. The HS classification
 * is treaty-pinned and updated only every ~5 years, so this static
 * snapshot is canonical.
 */

export const HS_HEADING_NAMES: Record<string, string> = {
  '0101': 'Horses, asses, mules and hinnies',
  '0102': 'Bovine animals',
  '0103': 'Swine',
  '0104': 'Sheep and goats',
  '0105': 'Poultry',
  '0106': 'Animals',
  '0201': 'Meat of bovine animals',
  '0202': 'Meat of bovine animals',
  '0203': 'Meat of swine',
  '0204': 'Meat of sheep or goats',
  '0205': 'Meat',
  '0206': 'Edible offal of bovine animals, swine, sheep, goats, hors...',
  '0207': 'Meat and edible offal of poultry',
  '0208': 'Meat and edible meat offal, n.e.c. in chapter 2',
  '0209': 'Pig fat, free of lean meat, and poultry fat, not rendered...',
  '0210': 'Meat and edible meat offal',
  '0301': 'Fish',
  '0302': 'Fish',
  '0303': 'Fish',
  '0304': 'Fish fillets and other fish meat (whether or not minced)',
  '0305': 'Fish, dried, salted or in brine',
  '0306': 'Crustaceans',
  '0307': 'Molluscs',
  '0308': 'Aquatic invertebrates other than crustaceans and molluscs...',
  '0309': 'Flours, meals and pellets of fish, crustaceans, molluscs ...',
  '0401': 'Milk and cream',
  '0402': 'Milk and cream',
  '0403': 'Yogurt',
  '0404': 'Whey and products consisting of natural milk constituents',
  '0405': 'Butter and other fats and oils derived from milk',
  '0406': 'Cheese and curd',
  '0407': 'Birds' eggs, in shell',
  '0408': 'Birds' eggs, not in shell',
  '0409': 'Honey',
  '0410': 'Animal products',
  '0501': 'Human hair',
  '0502': 'Pigs', hogs' or boars' bristles and hair',
  '0504': 'Guts, bladders and stomachs of animals (other than fish)',
  '0505': 'Skins and other parts of birds with feathers, down',
  '0506': 'Bones and horn-cores, unworked, defatted, simply prepared...',
  '0507': 'Ivory, tortoise-shell, whalebone and whalebone hair, horn...',
  '0508': 'Coral and similar materials, unworked or simply prepared,...',
  '0510': 'Ambergris, castoreum, civet and musk',
  '0511': 'Animal products not elsewhere specified or included',
  '0601': 'Bulbs, tubers, tuberous roots, corms, crowns and rhizomes',
  '0602': 'Plants, live',
  '0603': 'Flowers',
  '0604': 'Foliage, branches and other parts of plants, without flow...',
  '0701': 'Potatoes',
  '0702': 'Tomatoes',
  '0703': 'Onions, shallots, garlic, leeks and other alliaceous vege...',
  '0704': 'Cabbages, cauliflowers, kohlrabi, kale and similar edible...',
  '0705': 'Lettuce (lactuca sativa) and chicory (cichorium spp.) fre...',
  '0706': 'Carrots, turnips, salad beetroot, salsify, celeriac, radi...',
  '0707': 'Cucumbers and gherkins',
  '0708': 'Leguminous vegetables',
  '0709': 'Vegetables',
  '0710': 'Vegetables (uncooked or cooked by steaming or boiling in ...',
  '0711': 'Vegetables provisionally preserved, but unsuitable in tha...',
  '0712': 'Vegetables, dried',
  '0713': 'Vegetables, leguminous',
  '0714': 'Manioc, arrowroot, salep, Jerusalem artichokes, sweet pot...',
  '0801': 'Nuts, edible',
  '0802': 'Nuts (excluding coconuts, Brazils and cashew nuts)',
  '0803': 'Bananas, including plantains',
  '0804': 'Dates, figs, pineapples, avocados, guavas, mangoes and ma...',
  '0805': 'Citrus fruit',
  '0806': 'Grapes',
  '0807': 'Melons (including watermelons) and papaws (papayas)',
  '0808': 'Apples, pears and quinces',
  '0809': 'Apricots, cherries, peaches (including nectarines), plums...',
  '0810': 'Fruit, fresh',
  '0811': 'Fruit and nuts',
  '0812': 'Fruit and nuts provisionally preserved, but unsuitable in...',
  '0813': 'Fruit, dried, other than that of heading no. 0801 to 0806',
  '0814': 'Peel of citrus fruit or melons (including watermelons)',
  '0901': 'Coffee, whether or not roasted or decaffeinated',
  '0902': 'Tea',
  '0903': 'Mate',
  '0904': 'Pepper of the genus piper',
  '0905': 'Vanilla',
  '0906': 'Cinnamon and cinnamon-tree flowers',
  '0907': 'Cloves (whole fruit, cloves and stems)',
  '0908': 'Nutmeg, mace and cardamoms',
  '0909': 'Seeds of anise, badian, fennel, coriander, cumin, caraway...',
  '0910': 'Ginger, saffron, tumeric (curcuma), thyme, bay leaves, cu...',
  '1001': 'Wheat and meslin',
  '1002': 'Rye',
  '1003': 'Barley',
  '1004': 'Oats',
  '1005': 'Maize (corn)',
  '1006': 'Rice',
  '1007': 'Grain sorghum',
  '1008': 'Buckwheat, millet and canary seeds',
  '1101': 'Wheat or meslin flour',
  '1102': 'Cereal flours',
  '1103': 'Cereal groats',
  '1104': 'Cereal grains otherwise worked (e.g. hulled, rolled, flak...',
  '1105': 'Flour, meal, powder, flakes, granules and pellets of pota...',
  '1106': 'Flour, meal and powder',
  '1107': 'Malt',
  '1108': 'Starches',
  '1109': 'Wheat gluten',
  '1201': 'Soya beans, whether or not broken',
  '1202': 'Ground-nuts',
  '1203': 'Copra',
  '1204': 'Oil seeds',
  '1205': 'Rape or colza seeds',
  '1206': 'Sunflower seeds',
  '1207': 'Oil seeds and oleaginous fruits, n.e.c. in chapter 12',
  '1208': 'Flours and meals of oil seeds or oleaginous fruits',
  '1209': 'Seeds, fruit and spores',
  '1210': 'Hop cones, fresh or dried, whether or not ground, powdere...',
  '1211': 'Plants and parts of plants (including seeds and fruits), ...',
  '1212': 'Locust beans, seaweeds and other algae, sugar beet, sugar...',
  '1213': 'Cereal straw and husks, unprepared',
  '1214': 'Swedes, mangolds, fodder roots, hay, lucerne (alfalfa), c...',
  '1301': 'Lac',
  '1302': 'Vegetable saps and extracts',
  '1401': 'Vegetable materials of a kind used primarily for plaiting',
  '1404': 'Vegetable products not elsewhere specified or included',
  '1501': 'Pig fat (including lard) and poultry fat, other than that...',
  '1502': 'Fats of bovine animals, sheep or goats, other than those ...',
  '1503': 'Lard stearin, lard oil, oleostearin, oleo-oil and tallow oil',
  '1504': 'Fats and oils and their fractions of fish or marine mammals',
  '1505': 'Wool grease and fatty substances derived therefrom (inclu...',
  '1506': 'Animal fats and oils and their fractions',
  '1507': 'Soya-bean oil and its fractions',
  '1508': 'Ground nut oil and its fractions',
  '1509': 'Olive oil and its fractions',
  '1510': 'Vegetable oils',
  '1511': 'Palm oil and its fractions',
  '1512': 'Sun-flower seed, safflower or cotton-seed oil and their f...',
  '1513': 'Coconut (copra), palm kernel or babassu oil and their fra...',
  '1514': 'Rape, colza or mustard oil and their fractions',
  '1515': 'Fixed vegetable or microbial fats and oils n.e.c. in chap...',
  '1516': 'Animal, vegetable or microbial fats and oils and their fr...',
  '1517': 'Margarine',
  '1518': 'Animal, vegetable or microbial fats, oils and their fract...',
  '1520': 'Glycerol, crude',
  '1521': 'Vegetable waxes (other than triglycerides), beeswax, othe...',
  '1522': 'Degras',
  '1601': 'Sausages and similar products, of meat, meat offal, blood...',
  '1602': 'Prepared or preserved meat, meat offal, blood or insects',
  '1603': 'Extracts and juices of meat, fish or crustaceans, mollusc...',
  '1604': 'Prepared or preserved fish',
  '1605': 'Crustaceans, molluscs and other aquatic invertebrates, pr...',
  '1701': 'Cane or beet sugar and chemically pure sucrose, in solid ...',
  '1702': 'Sugars, including lactose, maltose, glucose or fructose i...',
  '1703': 'Molasses',
  '1704': 'Sugar confectionery (including white chocolate), not cont...',
  '1801': 'Cocoa beans',
  '1802': 'Cocoa',
  '1803': 'Cocoa',
  '1804': 'Cocoa',
  '1805': 'Cocoa',
  '1806': 'Chocolate and other food preparations containing cocoa',
  '1901': 'Malt extract',
  '1902': 'Pasta',
  '1903': 'Tapioca and substitutes therefor prepared from starch',
  '1904': 'Prepared foods obtained by swelling or roasting cereals o...',
  '1905': 'Bread, pastry, cakes, biscuits, other bakers' wares, whet...',
  '2001': 'Vegetables, fruit, nuts and other edible parts of plants',
  '2002': 'Tomatoes',
  '2003': 'Mushrooms and truffles, prepared or preserved other than ...',
  '2004': 'Vegetables preparations n.e.c.',
  '2005': 'Vegetables preparations n.e.c.',
  '2006': 'Vegetables, fruit, nuts, fruit-peel and other parts of pl...',
  '2007': 'Jams, fruit jellies, marmalades, fruit or nut puree and f...',
  '2008': 'Fruit, nuts and other edible parts of plants',
  '2009': 'Fruit or nut juices (including grape must and coconut wat...',
  '2101': 'Extracts, essences, concentrates of coffee, tea or mate',
  '2102': 'Yeasts (active or inactive)',
  '2103': 'Sauces and preparations therefor',
  '2104': 'Soups and broths and preparations therefor',
  '2105': 'Ice cream and other edible ice',
  '2106': 'Food preparations not elsewhere specified or included',
  '2201': 'Waters, including natural or artificial mineral waters an...',
  '2202': 'Waters, including mineral and aerated waters, containing ...',
  '2203': 'Beer made from malt',
  '2204': 'Wine of fresh grapes, including fortified wines',
  '2205': 'Vermouth and other wine of fresh grapes, flavoured with p...',
  '2206': 'Fermented beverages, n.e.c. in chapter 22',
  '2207': 'Ethyl alcohol, undenatured',
  '2208': 'Ethyl alcohol, undenatured',
  '2209': 'Vinegar and substitutes for vinegar obtained from acetic ...',
  '2301': 'Flours, meal and pellets, of meat or meat offal, of fish ...',
  '2302': 'Bran, sharps and other residues',
  '2303': 'Residues of starch manufacture, similar residues',
  '2304': 'Oil-cake and other solid residues',
  '2305': 'Oil-cake and other solid residues',
  '2306': 'Oil-cake and other solid residues',
  '2307': 'Wine lees',
  '2308': 'Vegetable materials and vegetable waste, vegetable residu...',
  '2309': 'Preparations of a kind used in animal feeding',
  '2401': 'Tobacco, unmanufactured',
  '2402': 'Cigars, cheroots, cigarillos and cigarettes',
  '2403': 'Manufactured tobacco and manufactured tobacco substitutes...',
  '2404': 'Products containing tobacco, reconstituted tobacco, nicot...',
  '2501': 'Salt (including table salt and denatured salt)',
  '2502': 'Iron pyrites',
  '2503': 'Sulphur of all kinds',
  '2504': 'Graphite',
  '2505': 'Sands of all kinds',
  '2506': 'Quartz',
  '2507': 'Kaolin and other kaolinic clays',
  '2508': 'Clays',
  '2509': 'Chalk',
  '2510': 'Natural calcium phosphates',
  '2511': 'Natural barium sulphate (barytes)',
  '2512': 'Siliceous fossil meals (e.g. kieselguhr, tripolite and di...',
  '2513': 'Pumice stone',
  '2514': 'Slate, whether or not roughly trimmed or merely cut, by s...',
  '2515': 'Marble, travertine, ecaussine and other calcareous stone',
  '2516': 'Granite, porphyry, basalt, sandstone, other monumental an...',
  '2517': 'Pebbles, gravel, crushed stone for concrete aggregates fo...',
  '2518': 'Dolomite, whether or not calcined or sintered, including ...',
  '2519': 'Natural magnesium carbonate (magnesite)',
  '2520': 'Gypsum',
  '2521': 'Limestone flux',
  '2522': 'Quicklime, slaked lime and hydraulic lime',
  '2523': 'Portland cement, aluminous cement (ciment fondu), slag ce...',
  '2524': 'Asbestos',
  '2525': 'Mica, including splittings',
  '2526': 'Natural steatite',
  '2528': 'Natural borates and concentrates thereof (whether or not ...',
  '2529': 'Feldspar',
  '2530': 'Mineral substances not elsewhere specified or included',
  '2601': 'Iron ores and concentrates',
  '2602': 'Manganese ores and concentrates, including ferruginous ma...',
  '2603': 'Copper ores and concentrates',
  '2604': 'Nickel ores and concentrates',
  '2605': 'Cobalt ores and concentrates',
  '2606': 'Aluminium ores and concentrates',
  '2607': 'Lead ores and concentrates',
  '2608': 'Zinc ores and concentrates',
  '2609': 'Tin ores and concentrates',
  '2610': 'Chromium ores and concentrates',
  '2611': 'Tungsten ores and concentrates',
  '2612': 'Uranium or thorium ores and concentrates',
  '2613': 'Molybdenum ores and concentrates',
  '2614': 'Titanium ores and concentrates',
  '2615': 'Niobium, tantalum, vanadium or zirconium ores and concent...',
  '2616': 'Precious metal ores and concentrates',
  '2617': 'Ores and concentrates',
  '2618': 'Granulated slag (slag sand) from the manufacture of iron ...',
  '2619': 'Slag, dross',
  '2620': 'Slag, ash and residues',
  '2621': 'Slag and ash n.e.c. in chapter 26',
  '2701': 'Coal',
  '2702': 'Lignite',
  '2703': 'Peat',
  '2704': 'Coke and semi-coke',
  '2705': 'Coal gas, water gas, producer gas and similar gases, othe...',
  '2706': 'Tar distilled from coal, from lignite, peat and other min...',
  '2707': 'Oils and other products of the distillation of high tempe...',
  '2708': 'Pitch and pitch coke',
  '2709': 'Petroleum oils and oils obtained from bituminous minerals',
  '2710': 'Petroleum oils and oils from bituminous minerals, not crude',
  '2711': 'Petroleum gases and other gaseous hydrocarbons',
  '2712': 'Petroleum jelly',
  '2713': 'Petroleum coke, petroleum bitumen',
  '2714': 'Bitumen and asphalt, natural',
  '2715': 'Bituminous mixtures based on natural asphalt',
  '2716': 'Electrical energy',
  '2801': 'Fluorine, chlorine, bromine and iodine',
  '2802': 'Sulphur',
  '2803': 'Carbon',
  '2804': 'Hydrogen, rare gases and other non-metals',
  '2805': 'Alkali or alkaline-earth metals',
  '2806': 'Hydrogen chloride (hydrochloric acid)',
  '2807': 'Sulphuric acid',
  '2808': 'Nitric acid',
  '2809': 'Diphosphorus pentaoxide',
  '2810': 'Oxides of boron',
  '2811': 'Inorganic acids and other inorganic oxygen compounds of n...',
  '2812': 'Halides and halide oxides of non-metals',
  '2813': 'Sulphides of non-metals',
  '2814': 'Ammonia',
  '2815': 'Sodium hydroxide (caustic soda)',
  '2816': 'Hydroxide and peroxide of magnesium',
  '2817': 'Zinc',
  '2818': 'Aluminium oxide (including artificial corundum)',
  '2819': 'Chromium oxides and hydroxides',
  '2820': 'Manganese oxides',
  '2821': 'Iron oxides and hydroxides',
  '2822': 'Cobalt oxides and hydroxides',
  '2823': 'Titanium oxides',
  '2824': 'Lead oxides',
  '2825': 'Hydrazine and hydroxylamine and their inorganic salts',
  '2826': 'Fluorides',
  '2827': 'Chlorides',
  '2828': 'Hypochlorites',
  '2829': 'Chlorates and perchlorates',
  '2830': 'Sulphides',
  '2831': 'Dithionites and sulphoxylates',
  '2832': 'Sulphites',
  '2833': 'Sulphates',
  '2834': 'Nitrites',
  '2835': 'Phosphinates (hypophosphites), phosphonates (phosphites),...',
  '2836': 'Carbonates',
  '2837': 'Cyanides, cyanide oxides and complex cyanides',
  '2839': 'Silicates',
  '2840': 'Borates',
  '2841': 'Salts of oxometallic or peroxometallic acids',
  '2842': 'Salts of inorganic acids or peroxoacids, n.e.c. including...',
  '2843': 'Colloidal precious metals',
  '2844': 'Radioactive chemical elements and radioactive isotopes (i...',
  '2845': 'Isotopes other than those of heading no. 2844',
  '2846': 'Compounds, inorganic or organic, of rare-earth metals',
  '2847': 'Hydrogen peroxide',
  '2849': 'Carbides, whether or not chemically defined',
  '2850': 'Hydrides, nitrides, azides, silicides and borides, whethe...',
  '2852': 'Inorganic or organic compounds of mercury, excluding amal...',
  '2853': 'Phosphides, chemically defined or not, not ferrophosphorus',
  '2901': 'Acyclic hydrocarbons',
  '2902': 'Cyclic hydrocarbons',
  '2903': 'Halogenated derivatives of hydrocarbons',
  '2904': 'Sulphonated, nitrated or nitrosated derivatives of hydroc...',
  '2905': 'Acyclic alcohols and their halogenated, sulphonated, nitr...',
  '2906': 'Alcohols',
  '2907': 'Phenols',
  '2908': 'Phenols or phenol-alcohols',
  '2909': 'Ethers, ether-alcohols, ether-phenols, ether-alcohol-phen...',
  '2910': 'Epoxides, epoxyalcohols, epoxyphenols and epoxyethers',
  '2911': 'Acetals and hemiacetals',
  '2912': 'Aldehydes, whether or not with other oxygen function',
  '2913': 'Aldehydes',
  '2914': 'Ketones and quinones',
  '2915': 'Acids',
  '2916': 'Acids',
  '2917': 'Acids',
  '2918': 'Acids',
  '2919': 'Esters',
  '2920': 'Esters of other inorganic acids of non-metals (other than...',
  '2921': 'Amine-function compounds',
  '2922': 'Oxygen-function amino-compounds',
  '2923': 'Quaternary ammonium salts and hydroxides',
  '2924': 'Carboxyamide-function compounds',
  '2925': 'Carboxyimide-function compounds (including saccharin and ...',
  '2926': 'Nitrile-function compounds',
  '2927': 'Diazo-, azo- or azoxy-compounds',
  '2928': 'Organic derivatives of hydrazine or of hydroxylamine',
  '2929': 'Nitrogen-function compounds, n.e.c. in chapter 29',
  '2930': 'Organo-sulphur compounds',
  '2931': 'Other organo-inorganic compounds',
  '2932': 'Heterocyclic compounds with oxygen hetero-atom(s) only',
  '2933': 'Heterocyclic compounds with nitrogen hetero-atom(s) only',
  '2934': 'Nucleic acids and their salts, whether or not chemically ...',
  '2935': 'Sulphonamides',
  '2936': 'Provitamins, vitamins',
  '2937': 'Hormones, prostaglandins, thromboxanes and leukotrienes, ...',
  '2938': 'Glycosides, natural or reproduced by synthesis, and their...',
  '2939': 'Alkaloids',
  '2940': 'Sugars, chemically pure, other than sucrose, lactose, mal...',
  '2941': 'Antibiotics',
  '2942': 'Organic compounds',
  '3001': 'Glands and other organs (extracts, secretions thereof) fo...',
  '3002': 'Human blood',
  '3003': 'Medicaments',
  '3004': 'Medicaments',
  '3005': 'Wadding, gauze, bandages (dressings, adhesive plasters, p...',
  '3006': 'Pharmaceutical goods',
  '3101': 'Fertilizers',
  '3102': 'Fertilizers',
  '3103': 'Fertilizers',
  '3104': 'Fertilizers',
  '3105': 'Fertilizers',
  '3201': 'Tanning extracts of vegetable origin',
  '3202': 'Tanning substances',
  '3203': 'Colouring matter of vegetable or animal origin (including...',
  '3204': 'Synthetic organic colouring matter and preparations based...',
  '3205': 'Colour lakes',
  '3206': 'Colouring matter and preparations thereof n.e.c. in headi...',
  '3207': 'Pigments, prepared',
  '3208': 'Paints, varnishes',
  '3209': 'Paints and varnishes (including enamels and lacquers) bas...',
  '3210': 'Paints and varnishes (including enamels, lacquers and dis...',
  '3211': 'Driers',
  '3212': 'Pigments (metallic powders and flakes) dispersed in non-a...',
  '3213': 'Colours',
  '3214': 'Glaziers' putty, grafting putty, resin cements, caulking ...',
  '3215': 'Ink',
  '3301': 'Oils',
  '3302': 'Odoriferous substances and mixtures (including alcoholic ...',
  '3303': 'Perfumes and toilet waters',
  '3304': 'Cosmetic and toilet preparations',
  '3305': 'Hair preparations',
  '3306': 'Oral or dental hygiene preparations',
  '3307': 'Perfumery, cosmetic or toilet preparations',
  '3401': 'Soap',
  '3402': 'Organic surface-active agents (not soap)',
  '3403': 'Lubricating preparations and those used in oil or grease ...',
  '3404': 'Waxes',
  '3405': 'Polishes, creams, scouring pastes, powders and similar',
  '3406': 'Candles, tapers and the like',
  '3407': 'Modelling pastes, including those for children',
  '3501': 'Casein, caseinates and other casein derivatives',
  '3502': 'Albumins (including concentrates of two or more whey prot...',
  '3503': 'Gelatin (including gelatin in rectangular sheets, whether...',
  '3504': 'Peptones and their derivatives',
  '3505': 'Dextrins and other modified starches (e.g. pregelatinised...',
  '3506': 'Prepared glues and other prepared adhesives, n.e.c. or in...',
  '3507': 'Enzymes',
  '3601': 'Explosives',
  '3602': 'Prepared explosives, other than propellent powders',
  '3603': 'Safety fuses',
  '3604': 'Fireworks, signalling flares, rain rockets, fog signals a...',
  '3605': 'Matches',
  '3606': 'Ferro-cerium and other pyrophoric alloys in all forms',
  '3701': 'Photographic plates and film in the flat, sensitised, une...',
  '3702': 'Photographic film in rolls, sensitised, unexposed, of any...',
  '3703': 'Photographic paper, paperboard and textiles',
  '3704': 'Photographic plates, film, paper, paperboard and textiles...',
  '3705': 'Photographic plates and film',
  '3706': 'Cinematographic film',
  '3707': 'Chemical preparations for photographic uses (other than v...',
  '3801': 'Artificial graphite',
  '3802': 'Activated carbon',
  '3803': 'Tall oil, whether or not refined',
  '3804': 'Residual lyes from the manufacture of wood pulp, whether ...',
  '3805': 'Gum, wood or sulphate turpentine, other terpenic oils',
  '3806': 'Rosin and resin acids and derivatives thereof',
  '3807': 'Wood tar',
  '3808': 'Insecticides, rodenticides, fungicides, herbicides, anti-...',
  '3809': 'Finishing agents, dye carriers to accelerate the dyeing, ...',
  '3810': 'Metal-pickling preparations',
  '3811': 'Anti-knock preparations, oxidation and gum inhibitors, vi...',
  '3812': 'Prepared rubber accelerators',
  '3813': 'Preparations and charges for fire extinguishers',
  '3814': 'Organic composite solvents and thinners, not elsewhere sp...',
  '3815': 'Reaction initiators, reaction accelerators and catalytic ...',
  '3816': 'Refractory cements, mortars, concretes and similar compos...',
  '3817': 'Mixed alkylbenzenes and mixed alkylnaphthalenes, other th...',
  '3818': 'Chemical elements doped for use in electronics, in the fo...',
  '3819': 'Hydraulic brake fluids and other prepared liquids for hyd...',
  '3820': 'Anti-freezing preparations and prepared de-icing fluids',
  '3821': 'Prepared culture media for the development or maintenance...',
  '3822': 'Reagents',
  '3823': 'Industrial monocarboxylic fatty acids',
  '3824': 'Prepared binders for foundry moulds or cores',
  '3825': 'Residual products of the chemical or allied industries, n...',
  '3826': 'Biodiesel and mixtures thereof',
  '3827': 'Mixtures containing halogenated derivatives of methane, e...',
  '3901': 'Polymers of ethylene, in primary forms',
  '3902': 'Polymers of propylene or of other olefins, in primary forms',
  '3903': 'Polymers of styrene, in primary forms',
  '3904': 'Polymers of vinyl chloride or of other halogenated olefin...',
  '3905': 'Polymers of vinyl acetate or of other vinyl esters, in pr...',
  '3906': 'Acrylic polymers in primary forms',
  '3907': 'Polyacetals, other polyethers and epoxide resins, in prim...',
  '3908': 'Polyamides in primary forms',
  '3909': 'Amino-resins, phenolic resins and polyurethanes, in prima...',
  '3910': 'Silicones in primary forms',
  '3911': 'Petroleum resins, coumarone-indene resins, polyterpenes, ...',
  '3912': 'Cellulose and its chemical derivatives, n.e.c. or include...',
  '3913': 'Natural polymers (e.g. alginic acid) and modified natural...',
  '3914': 'Ion-exchangers',
  '3915': 'Waste, parings and scrap, of plastics',
  '3916': 'Monofilament of which any cross-sectional dimension excee...',
  '3917': 'Tubes, pipes and hoses and fittings thereof (for example,...',
  '3918': 'Floor coverings of plastics, self-adhesive or not, in rol...',
  '3919': 'Self-adhesive plates, sheets, film, foil, tape, strip and...',
  '3920': 'Plastics',
  '3921': 'Plastic plates, sheets, film, foil and strip n.e.c. in ch...',
  '3922': 'Sanitary ware',
  '3923': 'Plastic articles for the conveyance or packing of goods',
  '3924': 'Tableware, kitchenware, other household articles and hygi...',
  '3925': 'Plastics',
  '3926': 'Articles of plastics and articles of other materials of h...',
  '4001': 'Natural rubber, balata, gutta-percha, guayule, chicle and...',
  '4002': 'Synthetic rubber and factice derived from oils, in primar...',
  '4003': 'Reclaimed rubber in primary forms or in plates, sheets or...',
  '4004': 'Waste, parings and scrap of rubber (other than hard rubbe...',
  '4005': 'Compounded rubber, unvulcanised, in primary forms or in p...',
  '4006': 'Unvulcanised rubber in other forms (e.g. rods, tubes and ...',
  '4007': 'Vulcanised rubber thread and cord',
  '4008': 'Plates, sheets, strip, rods and profile shapes, of vulcan...',
  '4009': 'Tubes, pipes and hoses, of vulcanised rubber (other than ...',
  '4010': 'Conveyor or transmission belts or belting, of vulcanised ...',
  '4011': 'New pneumatic tyres, of rubber',
  '4012': 'Retreaded or used pneumatic tyres of rubber',
  '4013': 'Inner tubes, of rubber',
  '4014': 'Hygienic or pharmaceutical articles (including teats), of...',
  '4015': 'Articles of apparel and clothing accessories (including g...',
  '4016': 'Articles of vulcanised rubber other than hard rubber, n.e...',
  '4017': 'Hard rubber (e.g. ebonite) in all forms, including waste ...',
  '4101': 'Raw hides and skins of bovine (including buffalo) or equi...',
  '4102': 'Raw skins of sheep or lambs (fresh, salted, dried, limed,...',
  '4103': 'Raw hides and skins n.e.c in headings no. 4101, 4102',
  '4104': 'Tanned or crust hides and skins of bovine (including buff...',
  '4105': 'Tanned or crust skins of sheep and lambs, without wool on...',
  '4106': 'Tanned or crust hides and skins of other animals, without...',
  '4107': 'Leather further prepared after tanning or crusting, inclu...',
  '4112': 'Leather further prepared after tanning or crusting, inclu...',
  '4113': 'Leather further prepared after tanning or crusting, inclu...',
  '4114': 'Chamois (including combination chamois) leather',
  '4115': 'Composition leather with a basis of leather or leather fi...',
  '4201': 'Saddlery and harness for any animal (including traces, le...',
  '4202': 'Trunks',
  '4203': 'Articles of apparel and clothing accessories, of leather ...',
  '4205': 'Leather or composition leather articles n.e.c. in chapter 42',
  '4206': 'Articles of gut (other than silk-worm gut), of goldbeater...',
  '4301': 'Raw furskins (including heads, tails, paws, other pieces ...',
  '4302': 'Tanned or dressed furskins (including heads, tails, paws,...',
  '4303': 'Articles of apparel, clothing accessories and other artic...',
  '4304': 'Artificial fur and articles thereof',
  '4401': 'Fuel wood, in logs, billets, twigs, faggots or similar forms',
  '4402': 'Wood charcoal (including shell or nut charcoal), whether ...',
  '4403': 'Wood in the rough, whether or not stripped of bark or sap...',
  '4404': 'Hoopwood',
  '4405': 'Wood wool',
  '4406': 'Railway or tramway sleepers (cross-ties) of wood',
  '4407': 'Wood sawn or chipped lengthwise, sliced or peeled, whethe...',
  '4408': 'Sheets for veneering (including those obtained by slicing...',
  '4409': 'Wood (including strips, friezes for parquet flooring, not...',
  '4410': 'Particle board, oriented strand board (OSB) and similar b...',
  '4411': 'Fibreboard of wood or other ligneous materials, whether o...',
  '4412': 'Plywood, veneered panels and similar laminated wood',
  '4413': 'Densified wood, in blocks, plates, strips or profile shapes',
  '4414': 'Wooden frames',
  '4415': 'Packing cases, boxes, crates, drums and similar packings,...',
  '4416': 'Casks, barrels, vats, tubs and other coopers' products an...',
  '4417': 'Tools, tool bodies, tool handles, broom or brush bodies a...',
  '4418': 'Builders' joinery and carpentry of wood, including cellul...',
  '4419': 'Tableware and kitchenware, of wood',
  '4420': 'Wood marquetry and inlaid wood',
  '4421': 'Wooden articles n.e.c. in heading no. 4414 to 4420',
  '4501': 'Natural cork, raw or simply prepared',
  '4502': 'Natural cork, debacked or roughly squared, or in rectangu...',
  '4503': 'Cork',
  '4504': 'Agglomerated cork (with or without a binding substance) a...',
  '4601': 'Plaits and similar products of plaiting materials, assemb...',
  '4602': 'Basketwork, wickerwork and other articles, made directly ...',
  '4701': 'Wood pulp, mechanical wood pulp',
  '4702': 'Chemical wood pulp, dissolving grades',
  '4703': 'Chemical wood pulp, soda or sulphate, other than dissolvi...',
  '4704': 'Chemical wood pulp, sulphite, other than dissolving grades',
  '4705': 'Wood pulp obtained by a combination of mechanical and che...',
  '4706': 'Pulps of fibres derived from recovered (waste and scrap) ...',
  '4707': 'Waste and scrap of paper and paperboard',
  '4801': 'Newsprint, in rolls or sheets',
  '4802': 'Uncoated paper and paperboard, used for writing, printing...',
  '4803': 'Tissue, towel, napkin stock or similar',
  '4804': 'Uncoated kraft paper and paperboard, in rolls or sheets, ...',
  '4805': 'Uncoated paper and paperboard n.e.c., in rolls or sheets',
  '4806': 'Vegetable parchment, greaseproof papers, tracing papers, ...',
  '4807': 'Composite paper and paperboard, (made by sticking layers ...',
  '4808': 'Paper and paperboard, corrugated (with or without glued f...',
  '4809': 'Carbon paper, self copy paper, and other copying or trans...',
  '4810': 'Paper and paperboard, coated one or both sides with kaoli...',
  '4811': 'Paper, paperboard, cellulose wadding and webs of cellulos...',
  '4812': 'Filter blocks, slabs and plates of paper pulp',
  '4813': 'Cigarette paper, whether or not cut to size or in the for...',
  '4814': 'Wallpaper and similar wall coverings',
  '4816': 'Carbon paper, self-copy paper and other copying or transf...',
  '4817': 'Envelopes, letter cards, plain postcards and corresponden...',
  '4818': 'Toilet paper, width 36cm or less or cut to size/shape',
  '4819': 'Cartons, boxes, cases, bags and the like, of paper, paper...',
  '4820': 'Registers, account books, diaries and similar',
  '4821': 'Paper or paperboard labels of all kinds, whether or not p...',
  '4822': 'Bobbins, spools, cops and similar supports of paper pulp,...',
  '4823': 'Paper, paperboard, cellulose wadding and webs of cellulos...',
  '4901': 'Printed books, brochures, leaflets and similar printed ma...',
  '4902': 'Newspapers, journals and periodicals, whether or not illu...',
  '4903': 'Children's picture, drawing or colouring books',
  '4904': 'Music, printed or in manuscript, whether or not bound or ...',
  '4905': 'Maps and hydrographic or similar charts of all kinds, inc...',
  '4906': 'Plans and drawings',
  '4907': 'Unused postage, revenue or similar stamps of current or n...',
  '4908': 'Transfers (decalcomanias)',
  '4909': 'Printed or illustrated postcards',
  '4910': 'Calendars of any kind, printed, including calendar blocks',
  '4911': 'Printed matter, n.e.c., including printed pictures and ph...',
  '5001': 'Silk-worm cocoons suitable for reeling',
  '5002': 'Raw silk (not thrown)',
  '5003': 'Silk waste (including cocoons unsuitable for reeling, yar...',
  '5004': 'Silk',
  '5005': 'Yarn spun from silk waste, not put up for retail sale',
  '5006': 'Silk yarn and yarn spun from silk waste, put up for retai...',
  '5007': 'Woven fabrics of silk or of silk waste',
  '5101': 'Wool, not carded or combed',
  '5102': 'Fine or coarse animal hair, not carded or combed',
  '5103': 'Waste of wool or of fine or coarse animal hair, including...',
  '5104': 'Wool, or fine or coarse animal hair',
  '5105': 'Wool and fine or coarse animal hair',
  '5106': 'Yarn of carded wool, not put up for retail sale',
  '5107': 'Yarn of combed wool, not put up for retail sale',
  '5108': 'Yarn of fine animal hair (carded or combed), not put up f...',
  '5109': 'Yarn of wool or of fine animal hair, put up for retail sale',
  '5110': 'Yarn of coarse animal hair or of horsehair (including gim...',
  '5111': 'Woven fabrics of carded wool or of carded fine animal hair',
  '5112': 'Woven fabrics of combed wool or of combed fine animal hair',
  '5113': 'Woven fabrics of coarse animal hair or of horsehair',
  '5201': 'Cotton',
  '5202': 'Cotton waste (including yarn waste and garnetted stock)',
  '5203': 'Cotton, carded or combed',
  '5204': 'Cotton sewing thread, whether or not put up for retail sale',
  '5205': 'Cotton yarn (other than sewing thread), containing 85% or...',
  '5206': 'Cotton yarn (other than sewing thread), containing less t...',
  '5207': 'Cotton yarn (other than sewing thread), put up for retail...',
  '5208': 'Woven fabrics of cotton, containing 85% or more by weight...',
  '5209': 'Woven fabrics of cotton, containing 85% or more by weight...',
  '5210': 'Woven fabrics of cotton, containing less than 85% by weig...',
  '5211': 'Woven fabrics of cotton, containing less than 85% by weig...',
  '5212': 'Other woven fabrics of cotton, n.e.c. in chapter 52',
  '5301': 'Flax, raw or processed but not spun',
  '5302': 'True hemp (cannabis sativa L.), raw or processed but not ...',
  '5303': 'Jute and other textile bast fibres (not flax, true hemp a...',
  '5305': 'Coconut, abaca (Manila hemp or Musa textilis Nee), ramie ...',
  '5306': 'Flax yarn',
  '5307': 'Yarn of jute or of other textile bast fibres of heading n...',
  '5308': 'Yarn of other vegetable textile fibres',
  '5309': 'Woven fabrics of flax',
  '5310': 'Woven fabrics of jute, other textile bast fibres of headi...',
  '5311': 'Woven fabrics of other vegetable textile fibres',
  '5401': 'Sewing thread of man-made filaments, whether or not put u...',
  '5402': 'Synthetic filament yarn (other than sewing thread), not p...',
  '5403': 'Artificial filament yarn (other than sewing thread), not ...',
  '5404': 'Synthetic monofilament of 67 decitex or more, of which no...',
  '5405': 'Artificial monofilament of 67 decitex or more, no cross-s...',
  '5406': 'Man-made filament yarn (other than sewing thread), put up...',
  '5407': 'Woven fabrics of synthetic filament yarn, including woven...',
  '5408': 'Woven fabrics of artificial filament yarn including woven...',
  '5501': 'Synthetic filament tow',
  '5502': 'Artificial filament tow',
  '5503': 'Synthetic staple fibres, not carded, combed or otherwise ...',
  '5504': 'Artificial staple fibres, not carded, combed or otherwise...',
  '5505': 'Waste (including noils, yarn waste and garnetted stock), ...',
  '5506': 'Synthetic staple fibres, carded, combed or otherwise proc...',
  '5507': 'Artificial staple fibres, carded, combed or otherwise pro...',
  '5508': 'Sewing thread of man-made staple fibres, whether or not p...',
  '5509': 'Yarn (other than sewing thread) of synthetic staple fibre...',
  '5510': 'Yarn (other than sewing thread) of artificial staple fibr...',
  '5511': 'Yarn (not sewing thread), of man-made staple fibres, put ...',
  '5512': 'Woven fabrics of synthetic staple fibres, containing 85% ...',
  '5513': 'Woven fabrics of synthetic staple fibres, containing less...',
  '5514': 'Woven fabrics of synthetic staple fibres, containing less...',
  '5515': 'Woven fabrics of synthetic staple fibres, n.e.c. in chapt...',
  '5516': 'Woven fabrics of artificial staple fibres',
  '5601': 'Wadding of textile materials and articles thereof',
  '5602': 'Felt',
  '5603': 'Nonwovens',
  '5604': 'Rubber thread and cord, textile covered',
  '5605': 'Yarn',
  '5606': 'Yarn and strip and the like of heading no. 5404 or 5405, ...',
  '5607': 'Twine, cordage, ropes and cables, whether or not plaited ...',
  '5608': 'Twine, cordage or rope',
  '5609': 'Articles of yarn, strip or the like of heading no. 5404 o...',
  '5701': 'Carpets and other textile floor coverings',
  '5702': 'Carpets and other textile floor coverings',
  '5703': 'Carpets and other textile floor coverings (including turf)',
  '5704': 'Carpets and other textile floor coverings',
  '5705': 'Carpets and other textile floor coverings',
  '5801': 'Fabrics',
  '5802': 'Fabrics',
  '5803': 'Gauze',
  '5804': 'Tulles and other net fabrics',
  '5805': 'Tapestries',
  '5806': 'Fabrics',
  '5807': 'Labels, badges and similar articles',
  '5808': 'Braids in the piece',
  '5809': 'Fabrics, woven',
  '5810': 'Embroidery',
  '5811': 'Quilted textile products',
  '5901': 'Textile fabrics, gum or amylaceous substance coated, used...',
  '5902': 'Textile fabrics',
  '5903': 'Textile fabrics impregnated, coated, covered or laminated...',
  '5904': 'Linoleum, whether or not cut to shape',
  '5905': 'Textile wall coverings',
  '5906': 'Textile fabrics, rubberised',
  '5907': 'Textile fabrics',
  '5908': 'Textile wicks, woven, plaited or knitted',
  '5909': 'Textile hose piping and similar textile tubing',
  '5910': 'Textiles',
  '5911': 'Textile products and articles for technical uses',
  '6001': 'Fabrics',
  '6002': 'Fabrics',
  '6003': 'Fabrics',
  '6004': 'Fabrics',
  '6005': 'Fabrics',
  '6006': 'Fabrics',
  '6101': 'Coats',
  '6102': 'Coats',
  '6103': 'Suits, ensembles, jackets, blazers, trousers, bib and bra...',
  '6104': 'Suits, ensembles, jackets, dresses, skirts, divided skirt...',
  '6105': 'Shirts',
  '6106': 'Blouses, shirts and shirt-blouses',
  '6107': 'Underpants, briefs, nightshirts, pyjamas, bathrobes, dres...',
  '6108': 'Slips, petticoats, briefs, panties, nightdresses, pyjamas...',
  '6109': 'T-shirts, singlets and other vests',
  '6110': 'Jerseys, pullovers, cardigans, waistcoats and similar art...',
  '6111': 'Garments and clothing accessories, babies'',
  '6112': 'Track suits, ski suits and swimwear',
  '6113': 'Garments made up of knitted or crocheted fabrics of headi...',
  '6114': 'Garments',
  '6115': 'Hosiery',
  '6116': 'Gloves, mittens and mitts',
  '6117': 'Clothing accessories',
  '6201': 'Overcoats, car-coats, capes, cloaks, anoraks (including s...',
  '6202': 'Coats',
  '6203': 'Suits, ensembles, jackets, blazers, trousers, bib and bra...',
  '6204': 'Suits, ensembles, jackets, dresses, skirts, divided skirt...',
  '6205': 'Shirts',
  '6206': 'Blouses, shirts and shirt-blouses',
  '6207': 'Singlets and other vests, underpants, briefs, night-shirt...',
  '6208': 'Singlets and other vests, slips, petticoats, briefs, pant...',
  '6209': 'Garments and clothing accessories',
  '6210': 'Garments made up of fabrics of heading no. 5602, 5603, 59...',
  '6211': 'Track suits, swimwear and other garments (not knitted or ...',
  '6212': 'Brassieres, girdles, corsets, braces, suspenders, garters...',
  '6213': 'Handkerchiefs (not knitted or crocheted)',
  '6214': 'Shawls, scarves, mufflers, mantillas, veils and the like ...',
  '6215': 'Ties, bow ties and cravats (not knitted or crocheted)',
  '6216': 'Gloves, mittens and mitts (not knitted or crocheted)',
  '6217': 'Clothing accessories n.e.c.',
  '6301': 'Blankets and travelling rugs',
  '6302': 'Bed linen, table linen, toilet linen and kitchen linen',
  '6303': 'Curtains (including drapes) and interior blinds',
  '6304': 'Furnishing articles',
  '6305': 'Sacks and bags, of a kind used for the packing of goods',
  '6306': 'Tarpaulins, awnings and sunblinds',
  '6307': 'Textiles',
  '6308': 'Textiles',
  '6309': 'Textiles',
  '6310': 'Rags',
  '6401': 'Footwear',
  '6402': 'Footwear',
  '6403': 'Footwear',
  '6404': 'Footwear',
  '6405': 'Footwear',
  '6406': 'Footwear',
  '6501': 'Hat-forms, hat bodies and hoods of felt, neither blocked ...',
  '6502': 'Hat-shapes',
  '6504': 'Hats and other headgear',
  '6505': 'Hats and other headgear',
  '6506': 'Headgear',
  '6507': 'Head-bands, linings, covers, hat foundations, hat frames,...',
  '6601': 'Umbrellas',
  '6602': 'Walking-sticks, seat-sticks, whips, riding-crops and the ...',
  '6603': 'Trimmings, parts and accessories of articles of heading n...',
  '6701': 'Skin and other parts of birds with their feather or down',
  '6702': 'Flowers, foliage and fruit, artificial, and parts thereof',
  '6703': 'Human hair, dressed, thinned, bleached or otherwise worked',
  '6704': 'Wigs, false beards, eyebrows and eyelashes, switches and ...',
  '6801': 'Stone',
  '6802': 'Monumental or building stone, worked (except slate) and a...',
  '6803': 'Slate, worked',
  '6804': 'Millstones, grindstones, grinding wheels, etc without fra...',
  '6805': 'Abrasive powder or grain',
  '6806': 'Slag, rock wool and similar mineral wools',
  '6807': 'Asphalt or similar material',
  '6808': 'Panels, boards, tiles, blocks and the like',
  '6809': 'Plaster or compositions based on plaster',
  '6810': 'Cement, concrete or artificial stone',
  '6811': 'Asbestos-cement, of cellulose fibre-cement or the like',
  '6812': 'Fabricated asbestos fibres',
  '6813': 'Friction material and articles thereof (e.g. sheets, roll...',
  '6814': 'Mica',
  '6815': 'Stone or other mineral substances',
  '6901': 'Bricks, blocks, tiles and other ceramic goods of siliceou...',
  '6902': 'Refractory bricks, blocks, tiles and similar refractory c...',
  '6903': 'Ceramic goods',
  '6904': 'Ceramic building bricks, floor blocks, support or filler ...',
  '6905': 'Roofing tiles, chimney-pots, cowls, chimney liners, archi...',
  '6906': 'Ceramic pipes, conduits, guttering and pipe fittings',
  '6907': 'Ceramic flags and paving, hearth or wall tiles',
  '6909': 'Ceramic ware for laboratory, chemical, other technical uses',
  '6910': 'Ceramic sinks, wash basins, wash basin pedestals, baths, ...',
  '6911': 'Tableware, kitchenware, other household articles and toil...',
  '6912': 'Ceramic tableware, kitchenware, other household articles ...',
  '6913': 'Statuettes and other ornamental ceramic articles',
  '6914': 'Ceramic articles',
  '7001': 'Glass',
  '7002': 'Glass in balls (other than microspheres of heading no. 70...',
  '7003': 'Glass',
  '7004': 'Glass',
  '7005': 'Glass',
  '7006': 'Glass of heading no. 7003, 7004 or 7005, bent, edge-worke...',
  '7007': 'Safety glass, consisting of toughened (tempered) or lamin...',
  '7008': 'Glass',
  '7009': 'Glass mirrors',
  '7010': 'Carboys, bottles, flasks, jars, pots, phials, ampoules, c...',
  '7011': 'Glass envelopes (including bulbs and tubes), open and gla...',
  '7013': 'Glassware of a kind used for table, kitchen, toilet, offi...',
  '7014': 'Signalling glassware and optical elements of glass (other...',
  '7015': 'Clock, watch and similar glasses, glasses for non-correct...',
  '7016': 'Glass',
  '7017': 'Laboratory, hygienic or pharmaceutical glassware, whether...',
  '7018': 'Glass beads, imitation pearls, precious or semi-precious ...',
  '7019': 'Glass fibres (including glass wool) and articles thereof ...',
  '7020': 'Glass',
  '7101': 'Pearls',
  '7102': 'Diamonds, whether or not worked, but not mounted or set',
  '7103': 'Precious (excluding diamond) and semi-precious stone',
  '7104': 'Stones',
  '7105': 'Dust and powder of natural or synthetic precious or semi-...',
  '7106': 'Silver (including silver plated with gold or platinum)',
  '7107': 'Base metals clad with silver',
  '7108': 'Gold (including gold plated with platinum) unwrought or i...',
  '7109': 'Base metals or silver, clad with gold, not further worked...',
  '7110': 'Platinum',
  '7111': 'Base metals, silver or gold, clad with platinum',
  '7112': 'Waste and scrap of precious metal or of metal clad with p...',
  '7113': 'Jewellery articles and parts thereof, of precious metal o...',
  '7114': 'Articles of goldsmiths' or silversmiths' wares and parts ...',
  '7115': 'Articles of precious metal or of metal clad with precious...',
  '7116': 'Articles of natural or cultured pearls, precious or semi-...',
  '7117': 'Imitation jewellery',
  '7118': 'Coin',
  '7201': 'Pig iron and spiegeleisen in pigs, blocks or other primar...',
  '7202': 'Ferro-alloys',
  '7203': 'Ferrous products obtained by direct reduction of iron ore...',
  '7204': 'Ferrous waste and scrap',
  '7205': 'Granules and powders, of pig iron, spiegeleisen, iron or ...',
  '7206': 'Iron and non-alloy steel in ingots or other primary forms...',
  '7207': 'Iron or non-alloy steel',
  '7208': 'Iron or non-alloy steel',
  '7209': 'Iron or non-alloy steel',
  '7210': 'Iron or non-alloy steel',
  '7211': 'Iron or non-alloy steel',
  '7212': 'Iron or non-alloy steel',
  '7213': 'Iron or non-alloy steel',
  '7214': 'Iron or non-alloy steel',
  '7215': 'Iron or non-alloy steel',
  '7216': 'Iron or non-alloy steel, angles, shapes and sections',
  '7217': 'Wire of iron or non-alloy steel',
  '7218': 'Stainless steel in ingots or other primary forms',
  '7219': 'Stainless steel',
  '7220': 'Stainless steel',
  '7221': 'Stainless steel bars and rods, hot-rolled, in irregularly...',
  '7222': 'Stainless steel bars and rods, angles, shapes and sections',
  '7223': 'Stainless steel wire',
  '7224': 'Alloy steel in ingots or other primary forms, semi-finish...',
  '7225': 'Alloy steel flat-rolled products, of a width 600mm or more',
  '7226': 'Alloy steel flat-rolled products, of a width of less than...',
  '7227': 'Steel, alloy',
  '7228': 'Alloy steel bars, rods, shapes and sections',
  '7229': 'Wire of other alloy steel',
  '7301': 'Iron or steel sheet piling, whether or not drilled, punch...',
  '7302': 'Railway or tramway track constructions of iron or steel',
  '7303': 'Tubes, pipes and hollow profiles, of cast iron',
  '7304': 'Tubes, pipes and hollow profiles, seamless, of iron (othe...',
  '7305': 'Iron or steel (excluding cast iron)',
  '7306': 'Iron or steel (excluding cast iron)',
  '7307': 'Tube or pipe fittings (e.g. couplings, elbows, sleeves), ...',
  '7308': 'Structures of iron or steel and parts thereof',
  '7309': 'Reservoirs, tanks, vats and similar containers',
  '7310': 'Tanks, casks, drums, cans, boxes and similar containers, ...',
  '7311': 'Containers for compressed or liquefied gas, of iron or steel',
  '7312': 'Stranded wire, ropes, cables, plaited bands, slings and t...',
  '7313': 'Barbed wire of iron or steel',
  '7314': 'Cloth (including endless bands), grill, netting and fenci...',
  '7315': 'Chain and parts thereof, of iron or steel',
  '7316': 'Anchors, grapnels and parts thereof, of iron or steel',
  '7317': 'Nails, tacks, drawing pins, corrugated nails, staples (no...',
  '7318': 'Screws, bolts, nuts, coach screws, screw hooks, rivets, c...',
  '7319': 'Sewing and knitting needles, bodkins, crochet hooks, embr...',
  '7320': 'Springs and leaves for springs, of iron or steel',
  '7321': 'Stoves, ranges, grates, cookers (those with subsidiary bo...',
  '7322': 'Radiators for central heating, not electrically heated an...',
  '7323': 'Table, kitchen, other household articles and parts, of ir...',
  '7324': 'Sanitary ware and parts thereof, of iron or steel',
  '7325': 'Iron or steel',
  '7326': 'Iron or steel',
  '7401': 'Copper mattes',
  '7402': 'Copper',
  '7403': 'Copper',
  '7404': 'Copper',
  '7405': 'Copper',
  '7406': 'Copper',
  '7407': 'Copper',
  '7408': 'Copper wire',
  '7409': 'Copper plates, sheets and strip',
  '7410': 'Copper foil (whether or not printed or backed with paper,...',
  '7411': 'Copper tubes and pipes',
  '7412': 'Copper',
  '7413': 'Copper',
  '7415': 'Copper, nails, tacks, drawing pins, staples (not those of...',
  '7418': 'Copper',
  '7419': 'Copper',
  '7501': 'Nickel mattes',
  '7502': 'Nickel',
  '7503': 'Nickel',
  '7504': 'Nickel',
  '7505': 'Nickel',
  '7506': 'Nickel',
  '7507': 'Nickel',
  '7508': 'Nickel',
  '7601': 'Aluminium',
  '7602': 'Aluminium',
  '7603': 'Aluminium',
  '7604': 'Aluminium',
  '7605': 'Aluminium wire',
  '7606': 'Aluminium',
  '7607': 'Aluminium foil (whether or not printed or backed with pap...',
  '7608': 'Aluminium',
  '7609': 'Aluminium',
  '7610': 'Aluminium',
  '7611': 'Aluminium',
  '7612': 'Aluminium casks, drums, cans, boxes etc (including rigid,...',
  '7613': 'Aluminium',
  '7614': 'Aluminium',
  '7615': 'Aluminium',
  '7616': 'Aluminium',
  '7801': 'Lead',
  '7802': 'Lead',
  '7804': 'Lead',
  '7806': 'Lead',
  '7901': 'Zinc',
  '7902': 'Zinc',
  '7903': 'Zinc',
  '7904': 'Zinc',
  '7905': 'Zinc',
  '7907': 'Zinc',
  '8001': 'Tin',
  '8002': 'Tin',
  '8003': 'Tin',
  '8007': 'Tin',
  '8101': 'Tungsten (wolfram)',
  '8102': 'Molybdenum',
  '8103': 'Tantalum',
  '8104': 'Magnesium',
  '8105': 'Cobalt',
  '8106': 'Bismuth',
  '8108': 'Titanium',
  '8109': 'Zirconium',
  '8110': 'Antimony',
  '8111': 'Manganese',
  '8112': 'Beryllium, chromium, hafnium, rhenium, thallium, cadmium,...',
  '8113': 'Cermets',
  '8201': 'Tools, hand',
  '8202': 'Tools, hand',
  '8203': 'Tools, hand',
  '8204': 'Tools, hand',
  '8205': 'Tools, hand',
  '8206': 'Tools, hand',
  '8207': 'Tools, interchangeable',
  '8208': 'Knives and cutting blades, for machines or for mechanical...',
  '8209': 'Tools',
  '8210': 'Tools',
  '8211': 'Knives',
  '8212': 'Razors and razor blades',
  '8213': 'Scissors',
  '8214': 'Cutlery',
  '8215': 'Cutlery',
  '8301': 'Padlocks and locks (key, combination, electrically operat...',
  '8302': 'Base metal mountings, fittings and similar articles for f...',
  '8303': 'Safes',
  '8304': 'Office equipment',
  '8305': 'Stationery',
  '8306': 'Bells, gongs and the like',
  '8307': 'Tubing',
  '8308': 'Clasps, frames with clasps, buckles, buckle-clasps, hooks...',
  '8309': 'Stoppers, caps, lids (including crown corks, screw caps, ...',
  '8310': 'Sign plates, name plates, address plates and similar plat...',
  '8311': 'Wires, rods, tubes, plates, electrodes of base metal or m...',
  '8401': 'Nuclear reactors',
  '8402': 'Boilers',
  '8403': 'Central heating boilers',
  '8404': 'Auxiliary plant for use with boilers of heading no. 8402 ...',
  '8405': 'Generators for producer or water gas with or without thei...',
  '8406': 'Turbines',
  '8407': 'Reciprocating or rotary internal combustion piston engines',
  '8408': 'Compression-ignition internal combustion piston engines (...',
  '8409': 'Parts suitable for use solely or principally with the eng...',
  '8410': 'Turbines',
  '8411': 'Turbo-jets, turbo-propellers and other gas turbines',
  '8412': 'Engines and motors',
  '8413': 'Pumps',
  '8414': 'Air or vacuum pumps, air or other gas compressors and fans',
  '8415': 'Air conditioning machines',
  '8416': 'Furnace burners for liquid fuel, for pulverised solid fue...',
  '8417': 'Furnaces and ovens',
  '8418': 'Refrigerators, freezers and other refrigerating or freezi...',
  '8419': 'Machinery, plant (not domestic), or laboratory equipment',
  '8420': 'Machines',
  '8421': 'Centrifuges, including centrifugal dryers',
  '8422': 'Dish washing machines',
  '8423': 'Weighing machines',
  '8424': 'Mechanical appliances for projecting, dispersing or spray...',
  '8425': 'Pulley tackle and hoists other than skip hoists',
  '8426': 'Derricks, cranes, including cable cranes, mobile lifting ...',
  '8427': 'Fork-lift and other works trucks',
  '8428': 'Lifting, handling, loading or unloading machinery',
  '8429': 'Bulldozers, graders, levellers, scrapers, angledozers, me...',
  '8430': 'Moving, grading, levelling, scraping, excavating, tamping...',
  '8431': 'Machinery parts',
  '8432': 'Agricultural, horticultural or forestry machinery for soi...',
  '8433': 'Harvesting and threshing machinery, straw and fodder bale...',
  '8434': 'Milking machines and dairy machinery',
  '8435': 'Presses, crushers and similar machinery',
  '8436': 'Agricultural, horticultural, forestry, poultry-keeping, b...',
  '8437': 'Machines for cleaning, sorting, grading seed, grain, drie...',
  '8438': 'Machinery n.e.c. in this chapter, for the industrial prep...',
  '8439': 'Machinery',
  '8440': 'Book-binding machinery',
  '8441': 'Machines',
  '8442': 'Machinery, apparatus and equipment (excluding machines of...',
  '8443': 'Printing machinery',
  '8444': 'Textile machinery',
  '8445': 'Textile machinery',
  '8446': 'Weaving machines (looms)',
  '8447': 'Knitting machines, stitch-bonding machines and machines f...',
  '8448': 'Machinery, auxiliary',
  '8449': 'Machinery',
  '8450': 'Household or laundry-type washing machines',
  '8451': 'Machinery (not of heading no. 8450) for washing, cleaning...',
  '8452': 'Sewing machines',
  '8453': 'Machinery for preparing, tanning or working hides, skins ...',
  '8454': 'Converters, ladles, ingot moulds and casting machines',
  '8455': 'Metal-rolling mills and rolls therefor',
  '8456': 'Machine-tools',
  '8457': 'Machining centres, unit construction machines (single sta...',
  '8458': 'Lathes for removing metal',
  '8459': 'Machine-tools',
  '8460': 'Machine-tools',
  '8461': 'Machine-tools',
  '8462': 'Machine-tools (including presses) for working metal by fo...',
  '8463': 'Machine-tools',
  '8464': 'Machine-tools',
  '8465': 'Machine-tools',
  '8466': 'Parts & accessories suited for use only/mainly with machi...',
  '8467': 'Tools',
  '8468': 'Machinery and apparatus for soldering, brazing, welding, ...',
  '8470': 'Calculating machines and pocket-size data recording, repr...',
  '8471': 'Automatic data processing machines and units thereof, mag...',
  '8472': 'Office machines',
  '8473': 'Machinery',
  '8474': 'Machinery for sorting, screening, separating, washing, cr...',
  '8475': 'Machines',
  '8476': 'Automatic goods-vending machines (e.g. postage stamp, cig...',
  '8477': 'Machinery',
  '8478': 'Machinery',
  '8479': 'Machinery and mechanical appliances',
  '8480': 'Moulding boxes for metal foundry, moulding patterns, moul...',
  '8481': 'Taps, cocks, valves and similar appliances for pipes, boi...',
  '8482': 'Ball or roller bearings',
  '8483': 'Transmission shafts (including cam and crank) and cranks',
  '8484': 'Gaskets and similar joints of metal sheeting combined wit...',
  '8485': 'Machines for additive manufacturing',
  '8486': 'Machines and apparatus of a kind used solely or principal...',
  '8487': 'Machinery parts',
  '8501': 'Electric motors and generators (excluding generating sets)',
  '8502': 'Electric generating sets and rotary converters',
  '8503': 'Electric motors and generators',
  '8504': 'Electric transformers, static converters (e.g. rectifiers...',
  '8505': 'Electro-magnets',
  '8506': 'Cells and batteries',
  '8507': 'Electric accumulators, including separators therefor',
  '8508': 'Vacuum cleaners',
  '8509': 'Electro-mechanical domestic appliances',
  '8510': 'Shavers, hair clippers and hair removing appliances, with...',
  '8511': 'Ignition or starting equipment',
  '8512': 'Lighting or visual signalling equipment (excluding articl...',
  '8513': 'Lamps',
  '8514': 'Industrial or laboratory electric furnaces and ovens (inc...',
  '8515': 'Electric (electrically heated gas) soldering, brazing, we...',
  '8516': 'Electric water, space, soil heaters',
  '8517': 'Telephone sets, including smartphones and other telephone...',
  '8518': 'Microphones and their stands',
  '8519': 'Sound recording or reproducing apparatus',
  '8521': 'Video recording or reproducing apparatus',
  '8522': 'Sound or video recording apparatus',
  '8523': 'Discs, tapes, solid-state non-volatile storage devices, s...',
  '8524': 'Flat panel display modules, whether or not incorporating ...',
  '8525': 'Transmission apparatus for radio-broadcasting or televisi...',
  '8526': 'Radar apparatus, radio navigational aid apparatus and rad...',
  '8527': 'Reception apparatus for radio-broadcasting, whether or no...',
  '8528': 'Monitors and projectors, not incorporating television rec...',
  '8529': 'Transmission apparatus',
  '8530': 'Signalling, safety or traffic control equipment',
  '8531': 'Signalling apparatus',
  '8532': 'Electrical capacitors',
  '8533': 'Electrical resistors (including rheostats and potentiomet...',
  '8534': 'Circuits',
  '8535': 'Electrical apparatus for switching, protecting electrical...',
  '8536': 'Electrical apparatus for switching, protecting electrical...',
  '8537': 'Boards, panels, consoles, desks, cabinets, bases with app...',
  '8538': 'Electrical apparatus',
  '8539': 'Lamps',
  '8540': 'Thermionic, cold cathode or photo-cathode valves and tube...',
  '8541': 'Semiconductor devices (e.g. diodes, transistors, semicond...',
  '8542': 'Electronic integrated circuits',
  '8543': 'Electrical machines and apparatus',
  '8544': 'Insulated wire, cable and other electric conductors, conn...',
  '8545': 'Carbon electrodes, carbon brushes, lamp carbons, battery ...',
  '8546': 'Electrical insulators of any material',
  '8547': 'Insulating fittings',
  '8548': 'Electrical parts of machinery or apparatus',
  '8549': 'Electrical and electronic waste and scrap',
  '8601': 'Rail locomotives',
  '8602': 'Rail locomotives',
  '8603': 'Railway or tramway coaches, vans and trucks',
  '8604': 'Railway or tramway maintenance or service vehicles',
  '8605': 'Railway or tramway coaches',
  '8606': 'Railway or tramway goods vans and wagons',
  '8607': 'Railway or tramway locomotives or rolling stock',
  '8608': 'Railway or tramway track fixtures and fittings',
  '8609': 'Containers',
  '8701': 'Tractors',
  '8702': 'Vehicles',
  '8703': 'Motor cars and other motor vehicles',
  '8704': 'Vehicles',
  '8705': 'Special purpose motor vehicles',
  '8706': 'Chassis',
  '8707': 'Bodies',
  '8708': 'Motor vehicles',
  '8709': 'Works trucks, self-propelled, (not fitted with lifting or...',
  '8710': 'Tanks and other armoured fighting vehicles',
  '8711': 'Motorcycles (including mopeds) and cycles',
  '8712': 'Bicycles and other cycles',
  '8713': 'Carriages for disabled persons',
  '8714': 'Vehicles',
  '8715': 'Baby carriages and parts thereof',
  '8716': 'Trailers and semi-trailers',
  '8801': 'Balloons and dirigibles',
  '8802': 'Aircraft n.e.c. in heading no. 8801, except unmanned airc...',
  '8804': 'Parachutes (including dirigible parachutes and paraglider...',
  '8805': 'Aircraft launching gear, deck-arrestor or similar gear, g...',
  '8806': 'Unmanned aircraft',
  '8807': 'Aircraft',
  '8901': 'Cruise ships, excursion boats, ferry-boats, cargo ships, ...',
  '8902': 'Fishing vessels, factory ships and other vessels',
  '8903': 'Yachts and other vessels',
  '8904': 'Tugs and pusher craft',
  '8905': 'Light-vessels, fire-floats, dredgers, floating cranes, ot...',
  '8906': 'Vessels',
  '8907': 'Boats, floating structures, other (for e.g. rafts, tanks,...',
  '8908': 'Vessels and other floating structures',
  '9001': 'Optical fibres and optical fibre bundles',
  '9002': 'Lenses, prisms, mirrors and other optical elements, of an...',
  '9003': 'Frames and mountings',
  '9004': 'Spectacles, goggles and the like',
  '9005': 'Binoculars, monoculars, other optical telescopes, mountin...',
  '9006': 'Cameras, photographic (excluding cinematographic)',
  '9007': 'Cinematographic cameras and projectors, whether or not in...',
  '9008': 'Image projectors, other than cinematographic',
  '9010': 'Photographic (including cinematographic) laboratory appar...',
  '9011': 'Microscopes, compound optical',
  '9012': 'Microscopes (excluding optical microscopes)',
  '9013': 'Lasers, other than laser diodes',
  '9014': 'Navigational instruments and appliances',
  '9015': 'Surveying (including photogrammetrical surveying), hydrog...',
  '9016': 'Balances',
  '9017': 'Drawing, marking-out, mathematical calculating instrument...',
  '9018': 'Instruments and appliances used in medical, surgical, den...',
  '9019': 'Mechano-therapy, massage appliances',
  '9020': 'Breathing appliances and gas masks',
  '9021': 'Orthopaedic appliances',
  '9022': 'Apparatus based on the use of x-rays or of alpha, beta, g...',
  '9023': 'Instruments, apparatus and models, designed for demonstra...',
  '9024': 'Machines and appliances for testing the hardness, strengt...',
  '9025': 'Hydrometers and similar floating instruments, thermometer...',
  '9026': 'Instruments, apparatus for measuring or checking the flow...',
  '9027': 'Instruments and apparatus',
  '9028': 'Gas, liquid or electricity supply or production meters, i...',
  '9029': 'Revolution counter, production counters, taximeters, mile...',
  '9030': 'Instruments, apparatus for measuring, checking electrical...',
  '9031': 'Measuring or checking instruments, appliances and machine...',
  '9032': 'Regulating or controlling instruments and apparatus',
  '9033': 'Machines and appliances, instruments or apparatus of chap...',
  '9101': 'Wrist-watches, pocket-watches, stop-watches and other wat...',
  '9102': 'Wrist-watches, pocket-watches, stop-watches and other wat...',
  '9103': 'Clocks',
  '9104': 'Instrument panel clocks and clocks of a similar type for ...',
  '9105': 'Clocks, other, n.e.c.',
  '9106': 'Time of day recording apparatus and apparatus for measuri...',
  '9107': 'Time switches',
  '9108': 'Watch movements',
  '9109': 'Clock movements',
  '9110': 'Watch or clock movements, complete, unassembled or partly...',
  '9111': 'Watch cases and parts thereof',
  '9112': 'Clock cases and cases of a similar type for other goods o...',
  '9113': 'Watch straps, watch bands, watch bracelets and parts thereof',
  '9114': 'Clock or watch parts',
  '9201': 'Pianos',
  '9202': 'Musical instruments',
  '9205': 'Musical instruments',
  '9206': 'Musical instruments',
  '9207': 'Musical instruments',
  '9208': 'Musical boxes, fairground and mechanical street organs, m...',
  '9209': 'Musical instrument parts (for example, mechanisms for mus...',
  '9301': 'Military weapons',
  '9302': 'Revolvers and pistols',
  '9303': 'Firearms',
  '9304': 'Firearms',
  '9305': 'Firearms',
  '9306': 'Bombs, grenades, torpedoes, mines, missiles and similar m...',
  '9307': 'Arms',
  '9401': 'Seats (not those of heading no. 9402), whether or not con...',
  '9402': 'Furniture',
  '9403': 'Furniture and parts thereof, n.e.c. in chapter 94',
  '9404': 'Mattress supports',
  '9405': 'Luminaires and light fittings',
  '9406': 'Buildings',
  '9503': 'Tricycles, scooters, pedal cars and similar wheeled toys',
  '9504': 'Video game consoles and machines, articles for funfair, t...',
  '9505': 'Festive, carnival or other entertainment articles, includ...',
  '9506': 'Gymnastics, athletics, other sports (including table tenn...',
  '9507': 'Fishing rods, fish-hooks and other line fishing tackle',
  '9508': 'Travelling circuses and travelling menageries, amusement ...',
  '9601': 'Ivory, bone, tortoise-shell, horn, antlers, coral, mother...',
  '9602': 'Vegetable, mineral carving material and articles of these...',
  '9603': 'Brooms, brushes (including parts of machines), hand opera...',
  '9604': 'Hand sieves and hand riddles',
  '9605': 'Travel sets',
  '9606': 'Buttons, press-fasteners, snap-fasteners and press-studs,...',
  '9607': 'Slide fasteners and parts thereof',
  '9608': 'Pens',
  '9609': 'Pencils (not of heading no. 9608), crayons, pencil leads,...',
  '9610': 'Slates and boards, with writing or drawing surfaces, whet...',
  '9611': 'Stamps',
  '9612': 'Typewriter, similar ribbons, inked, otherwise prepared fo...',
  '9613': 'Cigarette lighters and other lighters, whether or not mec...',
  '9614': 'Smoking pipes (including pipe bowls) and cigar or cigaret...',
  '9615': 'Combs, hair-slides and similar',
  '9616': 'Scent sprays and similar toilet sprays and mounts and hea...',
  '9617': 'Vacuum flasks and other vacuum vessels, complete with cases',
  '9618': 'Tailors' dummies and other lay figures',
  '9619': 'Sanitary towels (pads) and tampons, napkins (diapers), na...',
  '9620': 'Monopods, bipods, tripods and similar articles',
  '9701': 'Paintings, drawings and pastels, executed entirely by hand',
  '9702': 'Engravings, prints and lithographs',
  '9703': 'Sculptures and statuary',
  '9704': 'Stamps, postage or revenue',
  '9705': 'Collections and collectors' pieces',
  '9706': 'Antiques',
  '9999': 'Commodities not specified according to kind',
};

/** Look up an HS 4-digit code's name; falls back to "HS XXXX". */
export function headingName(code: string): string {
  const padded = code.padStart(4, '0');
  return HS_HEADING_NAMES[padded] ?? `HS ${padded}`;
}