/**
 * Static GICS sector map for the top ~300 US stocks by market cap.
 *
 * This is the primary sector source for the portfolio color system.
 * It covers 95%+ of typical portfolio holdings with zero API calls.
 *
 * Values must match the 11 canonical GICS sector names in gicsColors.ts.
 * Source: official GICS classification, current as of 2025.
 *
 * To add a missing stock, append it here following the same pattern.
 */

export const STATIC_SECTOR_MAP: Record<string, string> = {
  // ── Information Technology ──────────────────────────────────────────
  AAPL:'Information Technology', MSFT:'Information Technology',
  NVDA:'Information Technology', AVGO:'Information Technology',
  ORCL:'Information Technology', CSCO:'Information Technology',
  ACN: 'Information Technology', IBM: 'Information Technology',
  TXN: 'Information Technology', QCOM:'Information Technology',
  NOW: 'Information Technology', INTU:'Information Technology',
  AMAT:'Information Technology', LRCX:'Information Technology',
  MU:  'Information Technology', KLAC:'Information Technology',
  ADI: 'Information Technology', MCHP:'Information Technology',
  CDNS:'Information Technology', SNPS:'Information Technology',
  FTNT:'Information Technology', PANW:'Information Technology',
  CRWD:'Information Technology', ANSS:'Information Technology',
  GLW: 'Information Technology', TEL: 'Information Technology',
  MPWR:'Information Technology', ENPH:'Information Technology',
  KEYS:'Information Technology', TDY: 'Information Technology',
  ASML:'Information Technology', SAP: 'Information Technology',
  STM: 'Information Technology', MKSI:'Information Technology',
  LSCC:'Information Technology', ONTO:'Information Technology',
  AMBA:'Information Technology', IPGP:'Information Technology',
  CREE:'Information Technology', IIVI:'Information Technology',
  VIAV:'Information Technology', COHU:'Information Technology',

  // ── Communication Services ──────────────────────────────────────────
  GOOGL:'Communication Services', GOOG:'Communication Services',
  META: 'Communication Services', NFLX:'Communication Services',
  DIS:  'Communication Services', CMCSA:'Communication Services',
  T:    'Communication Services', VZ:  'Communication Services',
  TMUS: 'Communication Services', CHTR:'Communication Services',
  WBD:  'Communication Services', PARA:'Communication Services',
  FOXA: 'Communication Services', FOX: 'Communication Services',
  OMC:  'Communication Services', IPG: 'Communication Services',
  TTWO: 'Communication Services', EA:  'Communication Services',
  NTES: 'Communication Services', SPOT:'Communication Services',
  PINS: 'Communication Services', SNAP:'Communication Services',
  MTCH: 'Communication Services', ZG:  'Communication Services',
  LYFT: 'Communication Services', UBER:'Communication Services',

  // ── Consumer Discretionary ──────────────────────────────────────────
  AMZN:'Consumer Discretionary', TSLA:'Consumer Discretionary',
  HD:  'Consumer Discretionary', LOW: 'Consumer Discretionary',
  MCD: 'Consumer Discretionary', SBUX:'Consumer Discretionary',
  NKE: 'Consumer Discretionary', TJX: 'Consumer Discretionary',
  BKNG:'Consumer Discretionary', ABNB:'Consumer Discretionary',
  MAR: 'Consumer Discretionary', HLT: 'Consumer Discretionary',
  GM:  'Consumer Discretionary', F:   'Consumer Discretionary',
  RIVN:'Consumer Discretionary', LCID:'Consumer Discretionary',
  ORLY:'Consumer Discretionary', AZO: 'Consumer Discretionary',
  BBY: 'Consumer Discretionary', EBAY:'Consumer Discretionary',
  YUM: 'Consumer Discretionary', DPZ: 'Consumer Discretionary',
  CMG: 'Consumer Discretionary', RCL: 'Consumer Discretionary',
  CCL: 'Consumer Discretionary', NCLH:'Consumer Discretionary',
  LVS: 'Consumer Discretionary', MGM: 'Consumer Discretionary',
  WYNN:'Consumer Discretionary', PHM: 'Consumer Discretionary',
  LEN: 'Consumer Discretionary', DHI: 'Consumer Discretionary',
  MELI:'Consumer Discretionary', FIGS:'Consumer Discretionary',
  LULU:'Consumer Discretionary', DECK:'Consumer Discretionary',
  TPR: 'Consumer Discretionary', RL:  'Consumer Discretionary',
  VFC: 'Consumer Discretionary', PVH: 'Consumer Discretionary',

  // ── Consumer Staples ────────────────────────────────────────────────
  WMT: 'Consumer Staples', COST:'Consumer Staples',
  PG:  'Consumer Staples', KO:  'Consumer Staples',
  PEP: 'Consumer Staples', PM:  'Consumer Staples',
  MO:  'Consumer Staples', MDLZ:'Consumer Staples',
  CL:  'Consumer Staples', KMB: 'Consumer Staples',
  GIS: 'Consumer Staples', K:   'Consumer Staples',
  HRL: 'Consumer Staples', CAG: 'Consumer Staples',
  SJM: 'Consumer Staples', MKC: 'Consumer Staples',
  HSY: 'Consumer Staples', TSN: 'Consumer Staples',
  MNST:'Consumer Staples', STZ: 'Consumer Staples',
  BF_B:'Consumer Staples', TAP: 'Consumer Staples',
  KR:  'Consumer Staples', SFM: 'Consumer Staples',
  CVS: 'Consumer Staples', WBA: 'Consumer Staples',
  PRGO:'Consumer Staples',

  // ── Health Care ─────────────────────────────────────────────────────
  LLY: 'Health Care', JNJ: 'Health Care',
  UNH: 'Health Care', ABBV:'Health Care',
  MRK: 'Health Care', TMO: 'Health Care',
  ABT: 'Health Care', DHR: 'Health Care',
  PFE: 'Health Care', BMY: 'Health Care',
  AMGN:'Health Care', GILD:'Health Care',
  ISRG:'Health Care', MDT: 'Health Care',
  SYK: 'Health Care', BSX: 'Health Care',
  EW:  'Health Care', BDX: 'Health Care',
  IQV: 'Health Care', CRL: 'Health Care',
  IDXX:'Health Care', MTD: 'Health Care',
  A:   'Health Care', HOLX:'Health Care',
  DXCM:'Health Care', PODD:'Health Care',
  INCY:'Health Care', ALNY:'Health Care',
  MRNA:'Health Care', BNTX:'Health Care',
  REGN:'Health Care', VRTX:'Health Care',
  AZN: 'Health Care', NVO: 'Health Care',
  RHHBY:'Health Care', SNY:'Health Care',
  HUM: 'Health Care', CI:  'Health Care',
  ELV: 'Health Care', CNC: 'Health Care',
  MCK: 'Health Care', CAH: 'Health Care',
  ABC: 'Health Care',

  // ── Financials ──────────────────────────────────────────────────────
  BRK_B:'Financials', JPM:'Financials',
  V:   'Financials', MA:  'Financials',
  BAC: 'Financials', WFC: 'Financials',
  GS:  'Financials', MS:  'Financials',
  BLK: 'Financials', C:   'Financials',
  AXP: 'Financials', SCHW:'Financials',
  USB: 'Financials', TFC: 'Financials',
  PNC: 'Financials', COF: 'Financials',
  DFS: 'Financials', SYF: 'Financials',
  PYPL:'Financials', FIS: 'Financials',
  FI:  'Financials', GPN: 'Financials',
  AIG: 'Financials', MET: 'Financials',
  PRU: 'Financials', AFL: 'Financials',
  ALL: 'Financials', PGR: 'Financials',
  CB:  'Financials', TRV: 'Financials',
  HIG: 'Financials', BK:  'Financials',
  STT: 'Financials', NTRS:'Financials',
  ICE: 'Financials', CME: 'Financials',
  NDAQ:'Financials', CBOE:'Financials',
  MSCI:'Financials', SPGI:'Financials',
  MCO: 'Financials', AMG: 'Financials',
  BEN: 'Financials', IVZ: 'Financials',

  // ── Industrials ─────────────────────────────────────────────────────
  RTX: 'Industrials', HON:'Industrials',
  UPS: 'Industrials', CAT:'Industrials',
  DE:  'Industrials', GE: 'Industrials',
  LMT: 'Industrials', NOC:'Industrials',
  GD:  'Industrials', BA: 'Industrials',
  TDG: 'Industrials', HWM:'Industrials',
  FDX: 'Industrials', CSX:'Industrials',
  NSC: 'Industrials', UNP:'Industrials',
  DAL: 'Industrials', UAL:'Industrials',
  AAL: 'Industrials', LUV:'Industrials',
  JBLU:'Industrials', SAVE:'Industrials',
  MMM: 'Industrials', EMR:'Industrials',
  ETN: 'Industrials', PH: 'Industrials',
  ROK: 'Industrials', AME:'Industrials',
  IEX: 'Industrials', XYL:'Industrials',
  RRX: 'Industrials', GNRC:'Industrials',
  PWR: 'Industrials', FAST:'Industrials',
  GWW: 'Industrials', MSC:'Industrials',
  ITW: 'Industrials', DOV:'Industrials',
  IR:  'Industrials', CARR:'Industrials',
  OTIS:'Industrials', WAB:'Industrials',
  GEV: 'Industrials', TIH:'Industrials',
  MOD: 'Industrials', QIMC:'Industrials',
  VSE: 'Industrials', ROLL:'Industrials',
  AXON:'Industrials', SAIC:'Industrials',
  BAH: 'Industrials', LDOS:'Industrials',
  DRS: 'Industrials', HII:'Industrials',
  TXT: 'Industrials', LHX:'Industrials',
  SPR: 'Industrials', KTOS:'Industrials',
  CACI:'Industrials', MANT:'Industrials',
  KEYW:'Industrials',

  // ── Energy ──────────────────────────────────────────────────────────
  XOM: 'Energy', CVX:'Energy',
  COP: 'Energy', EOG:'Energy',
  SLB: 'Energy', MPC:'Energy',
  PSX: 'Energy', VLO:'Energy',
  PXD: 'Energy', DVN:'Energy',
  HAL: 'Energy', BKR:'Energy',
  HES: 'Energy', OXY:'Energy',
  OKE: 'Energy', WMB:'Energy',
  KMI: 'Energy', EPD:'Energy',
  ET:  'Energy', MPLX:'Energy',
  PAA: 'Energy', AM: 'Energy',
  APA: 'Energy', MRO:'Energy',
  FANG:'Energy', LNG:'Energy',
  RRC: 'Energy', AR:  'Energy',
  CTRA:'Energy', SM: 'Energy',

  // ── Utilities ───────────────────────────────────────────────────────
  NEE: 'Utilities', DUK:'Utilities',
  SO:  'Utilities', D:  'Utilities',
  EXC: 'Utilities', SRE:'Utilities',
  AEP: 'Utilities', PEG:'Utilities',
  XEL: 'Utilities', WEC:'Utilities',
  ES:  'Utilities', CMS:'Utilities',
  DTE: 'Utilities', PPL:'Utilities',
  ETR: 'Utilities', FE: 'Utilities',
  CNP: 'Utilities', AES:'Utilities',
  NRG: 'Utilities', VST:'Utilities',
  EIX: 'Utilities', PCG:'Utilities',
  AWK: 'Utilities', WTR:'Utilities',

  // ── Real Estate ─────────────────────────────────────────────────────
  PLD: 'Real Estate', AMT:'Real Estate',
  EQIX:'Real Estate', CCI:'Real Estate',
  SPG: 'Real Estate', O:  'Real Estate',
  WELL:'Real Estate', DLR:'Real Estate',
  PSA: 'Real Estate', EXR:'Real Estate',
  AVB: 'Real Estate', EQR:'Real Estate',
  VTR: 'Real Estate', PEAK:'Real Estate',
  ARE: 'Real Estate', CBRE:'Real Estate',
  SBAC:'Real Estate', AMH:'Real Estate',
  MAA: 'Real Estate', UDR:'Real Estate',
  CPT: 'Real Estate', AIV:'Real Estate',
  KIM: 'Real Estate', REG:'Real Estate',
  BXP: 'Real Estate', SLG:'Real Estate',
  VNO: 'Real Estate', HIW:'Real Estate',

  // ── Materials ───────────────────────────────────────────────────────
  LIN: 'Materials', APD:'Materials',
  ECL: 'Materials', SHW:'Materials',
  FCX: 'Materials', NEM:'Materials',
  NUE: 'Materials', STLD:'Materials',
  CF:  'Materials', MOS:'Materials',
  ALB: 'Materials', PPG:'Materials',
  RPM: 'Materials', FMC:'Materials',
  IFF: 'Materials', CE: 'Materials',
  EMN: 'Materials', CTVA:'Materials',
  DD:  'Materials', DOW:'Materials',
  LYB: 'Materials', HUN:'Materials',
  WRK: 'Materials', PKG:'Materials',
  IP:  'Materials', SON:'Materials',
  CLF: 'Materials', MT: 'Materials',
  RIO: 'Materials', BHP:'Materials',
  VALE:'Materials', AA: 'Materials',
  X:   'Materials', SCCO:'Materials',
  // User portfolio stocks
  SCD: 'Materials', HGRAF:'Materials',
};

/**
 * Look up the GICS sector for a ticker from the static map.
 * Returns null if the ticker is not in the map.
 */
export function getStaticSector(ticker: string): string | null {
  return STATIC_SECTOR_MAP[ticker.toUpperCase()] ?? null;
}
