-- Daily market brief cache
-- One row per trading day. Generated once at 6am ET by the generate-daily-brief
-- edge function. Served read-only to all frontend users via RLS policy.

CREATE TABLE IF NOT EXISTS daily_briefs (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  date            DATE NOT NULL UNIQUE,
  headline        TEXT NOT NULL,
  market_regime   TEXT NOT NULL,
  sentiment_score INTEGER NOT NULL,
  vix             NUMERIC(6,2),
  summary         TEXT NOT NULL DEFAULT '',
  sectors         JSONB NOT NULL DEFAULT '[]',
  fear_greed      JSONB NOT NULL DEFAULT '{}',
  current_events  TEXT NOT NULL DEFAULT '',
  calendar        JSONB NOT NULL DEFAULT '[]',
  watch_today     TEXT NOT NULL DEFAULT '',
  generated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  model           TEXT NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS daily_briefs_date_idx ON daily_briefs (date DESC);

ALTER TABLE daily_briefs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "public read" ON daily_briefs
  FOR SELECT USING (true);

CREATE POLICY "service_role_write" ON daily_briefs
  FOR ALL
  USING (auth.role() = 'service_role')
  WITH CHECK (auth.role() = 'service_role');

COMMENT ON TABLE daily_briefs IS
  'AI-generated daily market brief. One row per trading day. Generated by generate-daily-brief edge function at 6am ET via pg_cron.';
